### PR TITLE
Remove current month from total revenue

### PR DESCRIPTION
**Pull request by browniefed**
Wasn't sure if this was a bug or not, but current month revenue is included in the Previous 6 Months. Wasn't sure if we wanted to keep these separate or not.

Accept, decline, whatever.

### CODE REVIEW

**Comment by trevordmiller** [comment]
Thanks for contributing @browniefed, I appreciate it. Yes, current month is meant to be a part of the previous section so I'm going to close this. But I do appreciate you thinking about it and we are happy to have your contributions in the future :)

**Comment by trevordmiller** [comment]
Hey @browniefed, we've discussed and thought about this more and I think you have a great idea here. Once we update our revenue endpoint to send back 7 months (6 past and 1 current), this PR would be great to merge in. I'll reopen it for now until then. Thank you again for your contribution! We really appreciate it :)

**Review by trevordmiller — APPROVED** [review]
This looks great @browniefed, thanks for adding tests. I'm going to merge this now so it will say "Last 5 months" but that number is dynamic so if/when we update the endpoints to return 7 months of revenue it will update to "Last 6 months" automatically on the client. Thanks again!

**Comment by browniefed** [comment]
👍

**Comment by trevordmiller** [comment]
Weird state in continuous integration; once passing I'll merge

**Comment by joelhooks** [comment]
@trevordmiller CI won't build from a fork. It's a problem with codeship generally.

**Comment by trevordmiller** [comment]
Weird, never experienced that with CI before. Glad we're moving to travis ha. I'll deal with this monday.

**Comment by trevordmiller** [comment]
This is working now:
image

Thanks again @browniefed.

**Comment by browniefed** [comment]
👍

**Pull request merged**
